apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: mayastor-3-sc
